dependencyDiscoverer: dependencyDiscoverer.cpp
	clang++ -Wall -Werror -std=c++17 -o dependencyDiscoverer dependencyDiscoverer.cpp -lpthread

dependencyDiscoverer50: dependencyDiscoverer50.cpp
	clang++ -Wall -Werror -std=c++17 -o dependencyDiscoverer50 dependencyDiscoverer50.cpp -lpthread

clean:
	rm -f *.o dependencyDiscoverer *~
